stages:
  - build
  - test
  - migrate
  - deploy

before_script:
  - cp $ENV_FILE .env

build-job:
  stage: build
  script:
    - docker build -t alohssh .

test-job:
  stage: test
  script:
    - echo "testing..."
    - sleep 10s

migrate-job:
  stage: migrate
  script:
    - docker compose run --rm migrate up

deploy-job:
  stage: deploy 
  script:
    - docker-compose down --remove-orphans
    - docker-compose up -d --build
    - R_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' alohssh)
    - if [ "$R_EXIT_CODE" -ne 0 ]; then
        echo "container failed with exit code $R_EXIT_CODE";
        docker logs alohssh;
        exit 1;
      fi  
    - sleep 5
    - docker-compose logs alohssh